name: Shell Commands on dev branch

on:
  push:
    branches: [ dev ]
    paths: 
      - 'butt-head/**'
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
